[build]
publish = "dist"
command = "yarn build"

[[redirects]]
	from = "/statistician.js"
	to = "https://plausible.io/js/plausible.js"
	status = 200
	force = true

[[redirects]]
	from = "/api/event"
	to = "https://plausible.io/api/event"
	status = 200
	force = true

[[redirects]]
	from = "/analytics"
	to = "https://plausible.io/towing.utf9k.net"
	status = 301
	force = false