name: Build and push
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-20.04
    permissions:
      deployments: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        id: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install yarn
        run: npm install -g yarn
      - name: Install Node dependencies
        run: yarn install
      - name: Build site
        run: yarn build
      - name: Publish to Cloudflare Pages
        id: cloudflare-publish
        if: ${{ !env.ACT }}
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 8e782a355544971b192db9e75d789dca
          projectName: 9kdotfiles
          directory: dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
      - uses: mshick/add-pr-comment@v2
        if: ${{ !env.ACT }}
        with:
          message: |
            🚀 This branch can be previewed at ${{ steps.cloudflare-publish.outputs.url }}